name: CI
on:
  push:
    branches:
      - automation/bors/try
  pull_request:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: cargo build --release
        run: cargo build --release